import { existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const PACKAGE_ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const VERSION: string = JSON.parse(
  readFileSync(join(PACKAGE_ROOT, "package.json"), "utf8"),
).version;

export const BLOCK_START = "<!-- ib:standard:start";
export const BLOCK_END = "<!-- ib:standard:end -->";

export type PlannedFile = { path: string; contents: string; mode: "replace" | "managed-block" };

function readAsset(...segments: string[]): string {
  return readFileSync(join(PACKAGE_ROOT, ...segments), "utf8");
}

function managedBlock(): string {
  return [
    `${BLOCK_START} v${VERSION} — generated by @inbeat/standards, edit in ib-toolkit -->`,
    readAsset("agents", "standard.md").trim(),
    BLOCK_END,
  ].join("\n");
}

export function applyManagedBlock(existing: string | null): string {
  const block = managedBlock();
  if (existing === null)
    return `# AGENTS.md\n\n${block}\n\n${readAsset("agents", "app-section.md")}`;
  const start = existing.indexOf(BLOCK_START);
  const end = existing.indexOf(BLOCK_END);
  if (start === -1 || end === -1 || end < start) return `${block}\n\n${existing}`;
  return existing.slice(0, start) + block + existing.slice(end + BLOCK_END.length);
}

function parseSkill(raw: string): { description: string; body: string } {
  const match = raw.match(/^---\n([\s\S]*?)\n---\n([\s\S]*)$/);
  if (!match) throw new Error("Skill is missing frontmatter");
  const description = match[1].match(/^description:\s*(.+)$/m)?.[1]?.trim() ?? "";
  return { description, body: match[2].trim() };
}

function skillFiles(): PlannedFile[] {
  const skillsDir = join(PACKAGE_ROOT, "skills");
  return readdirSync(skillsDir).flatMap((name) => {
    const raw = readAsset("skills", name, "SKILL.md");
    const { description, body } = parseSkill(raw);
    const rule = [
      "---",
      `description: ${description}`,
      "alwaysApply: false",
      "---",
      "",
      body,
      "",
    ].join("\n");
    return [
      {
        path: join(".cursor", "skills", name, "SKILL.md"),
        contents: raw,
        mode: "replace" as const,
      },
      {
        path: join(".claude", "skills", name, "SKILL.md"),
        contents: raw,
        mode: "replace" as const,
      },
      { path: join(".cursor", "rules", `${name}.mdc`), contents: rule, mode: "replace" as const },
    ];
  });
}

export function plan(appDir: string): PlannedFile[] {
  const agentsPath = join(appDir, "AGENTS.md");
  const existing = existsSync(agentsPath) ? readFileSync(agentsPath, "utf8") : null;
  return [
    { path: "AGENTS.md", contents: applyManagedBlock(existing), mode: "managed-block" },
    ...skillFiles(),
  ];
}

export function staleFiles(appDir: string): string[] {
  return plan(appDir)
    .filter(({ path, contents }) => {
      const target = join(appDir, path);
      return !existsSync(target) || readFileSync(target, "utf8") !== contents;
    })
    .map(({ path }) => path);
}

export function write(appDir: string): string[] {
  const stale = new Set(staleFiles(appDir));
  for (const file of plan(appDir).filter(({ path }) => stale.has(path))) {
    const target = join(appDir, file.path);
    mkdirSync(dirname(target), { recursive: true });
    writeFileSync(target, file.contents);
  }
  return [...stale];
}

const CLAUDE_FILES = ["CLAUDE.md", join(".claude", "CLAUDE.md"), "CLAUDE.local.md"];
const AGENTS_IMPORT = /^@AGENTS\.md\s*$/m;

// Claude Code reads AGENTS.md only when none of these files exist; otherwise it is ignored.
export function claudeFilesIgnoringAgents(appDir: string): string[] {
  return CLAUDE_FILES.filter((file) => {
    const path = join(appDir, file);
    return existsSync(path) && !AGENTS_IMPORT.test(readFileSync(path, "utf8"));
  });
}
