import {
  existsSync,
  mkdirSync,
  readdirSync,
  readFileSync,
  rmdirSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

export const PACKAGE_ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
export const VERSION: string = JSON.parse(
  readFileSync(join(PACKAGE_ROOT, "package.json"), "utf8"),
).version;

export const BLOCK_START = "<!-- ib:standard:start";
export const BLOCK_END = "<!-- ib:standard:end -->";

export type PlannedFile = { path: string; contents: string; mode: "replace" | "managed-block" };

function readAsset(...segments: string[]): string {
  return readFileSync(join(PACKAGE_ROOT, ...segments), "utf8");
}

function managedBlock(): string {
  return [
    `${BLOCK_START} — generated by @inbeat/standards, edit in ib-toolkit -->`,
    readAsset("agents", "standard.md").trim(),
    BLOCK_END,
  ].join("\n");
}

export function applyManagedBlock(existing: string | null): string {
  const block = managedBlock();
  if (existing === null)
    return `# AGENTS.md\n\n${block}\n\n${readAsset("agents", "app-section.md")}`;
  const start = existing.indexOf(BLOCK_START);
  const end = existing.indexOf(BLOCK_END);
  if (start === -1 || end === -1 || end < start) return `${block}\n\n${existing}`;
  return existing.slice(0, start) + block + existing.slice(end + BLOCK_END.length);
}

function skillNames(): string[] {
  return readdirSync(join(PACKAGE_ROOT, "skills"));
}

function skillFiles(): PlannedFile[] {
  return skillNames().map((name) => ({
    path: join(".agents", "skills", name, "SKILL.md"),
    contents: readAsset("skills", name, "SKILL.md"),
    mode: "replace" as const,
  }));
}

// Paths earlier versions generated for Claude Code and Cursor; sync deletes them.
function legacyPaths(): string[] {
  return skillNames().flatMap((name) => [
    join(".claude", "skills", name, "SKILL.md"),
    join(".cursor", "skills", name, "SKILL.md"),
    join(".cursor", "rules", `${name}.mdc`),
  ]);
}

function removeLegacyFiles(appDir: string): string[] {
  const removed = legacyPaths().filter((path) => existsSync(join(appDir, path)));
  for (const path of removed) {
    rmSync(join(appDir, path));
    for (let dir = dirname(join(appDir, path)); dir !== appDir; dir = dirname(dir)) {
      if (readdirSync(dir).length > 0) break;
      rmdirSync(dir);
    }
  }
  return removed;
}

export function plan(appDir: string): PlannedFile[] {
  const agentsPath = join(appDir, "AGENTS.md");
  const existing = existsSync(agentsPath) ? readFileSync(agentsPath, "utf8") : null;
  return [
    { path: "AGENTS.md", contents: applyManagedBlock(existing), mode: "managed-block" },
    ...skillFiles(),
  ];
}

export function staleFiles(appDir: string): string[] {
  return plan(appDir)
    .filter(({ path, contents }) => {
      const target = join(appDir, path);
      return !existsSync(target) || readFileSync(target, "utf8") !== contents;
    })
    .map(({ path }) => path)
    .concat(legacyPaths().filter((path) => existsSync(join(appDir, path))));
}

export function write(appDir: string): string[] {
  const stale = new Set(staleFiles(appDir));
  const written = plan(appDir).filter(({ path }) => stale.has(path));
  for (const file of written) {
    const target = join(appDir, file.path);
    mkdirSync(dirname(target), { recursive: true });
    writeFileSync(target, file.contents);
  }
  return [...written.map(({ path }) => path), ...removeLegacyFiles(appDir)];
}

const CLAUDE_FILES = ["CLAUDE.md", join(".claude", "CLAUDE.md"), "CLAUDE.local.md"];
const AGENTS_IMPORT = /^@AGENTS\.md\s*$/m;

// Claude Code reads AGENTS.md only when none of these files exist; otherwise it is ignored.
export function claudeFilesIgnoringAgents(appDir: string): string[] {
  return CLAUDE_FILES.filter((file) => {
    const path = join(appDir, file);
    return existsSync(path) && !AGENTS_IMPORT.test(readFileSync(path, "utf8"));
  });
}
